### PR TITLE
Fix eigen compilation problems

### PR DESCRIPTION
**Pull request by Lugatod**
Trying to fix encountered compilation problems with Eigen on some Linux distribution.

### CODE REVIEW

**Comment by VikingScientist** [comment]
This is a confirmed fix for Issue #62 for me.

**Comment by fredrikbk** [comment]
Great!

@fulviofarina I think this fixes the problem you had before your upgrade.

**Comment by fulviofarina** [comment]
Hello, thanks!.
I still get an error but at 57%, when using Ubuntu

r_index_expressions.cpp.o
[ 54%] Building CXX object src/CMakeFiles/simit.dir/lower/index_expressions/lower_matrix_multiply.cpp.o
[ 55%] Building CXX object src/CMakeFiles/simit.dir/lower/index_expressions/lower_scatter_workspace.cpp.o
[ 55%] Building CXX object src/CMakeFiles/simit.dir/lower/index_expressions/lower_tensor_utils.cpp.o
[ 56%] Building CXX object src/CMakeFiles/simit.dir/lower/index_expressions/lower_transpose.cpp.o
[ 57%] Linking CXX shared library ../lib/libsimit.so
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
src/CMakeFiles/simit.dir/build.make:2312: recipe for target 'lib/libsimit.so' failed
make[2]: *** [lib/libsimit.so] Error 1
CMakeFiles/Makefile2:96: recipe for target 'src/CMakeFiles/simit.dir/all' failed
make[1]: *** [src/CMakeFiles/simit.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

On the Windows10 Linux bash it works. So I guess it must be a missing library. I'll keep looking for it.

**Comment by fredrikbk** [comment]
Yeah, try using your package manager to install the z library.

**Comment by stephenchouca** [comment]
@fulviofarina: [this](http://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz) might help.

**Pull request merged**
